let a = 20;
let b = 10;
let c = 30;
let d = 2;
console.log("+ :" + (a+b));
console.log('- :' + (a-b));
console.log('* :' + (a*b));
console.log('/ :' + (a/b));
console.log('% :' + (a%b));
d++;
console.log(d**20);